### ISSUE TITLE
Should `geerlingguy.php` not be defined as a dependency in meta/main.yml?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-composer#28]
Without php, composer cannot be installed:

```
FAILED! => {"changed": false, "cmd": "php composer-installer.php", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

In my opinion, a dependency of php should be defined like in for example: https://github.com/030/ansible-sensu-client/blob/master/meta/main.yml#L17

Now I have to define `geerlingguy.php` manually and I also have to put it above `geerlingguy.composer`, while if dependency would have been used then the latter would install php first

**Comment by geerlingguy** [comment]
@030 - I typically use these 'soft' dependencies (e.g. "PHP needs to be installed, and I have a role you can use for that") rather than explicitly requiring another one of my roles. That way if you have a forked PHP role that you need for your environment, you can still use my Composer role... which doesn't require anything specific in my own PHP role, just 'I need PHP on the server'.
