### ISSUE TITLE
Installer Signature Comparison

### ISSUE THREAD

**Issue by robinmalburn** [geerlingguy/ansible-role-composer#40]
Looking at the main installation task for the role, I notice there's currently no signature comparison/check being ran before running the downloaded Composer installation script (as suggested in the [Composer docs](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md)).  Given that the installer isn't coming from a distro-maintained repository the signature check would at least give a little extra security, certainly at the very least against mitm concerns.

Would you consider adding support for the signature check to the role?  Or consider a pull request for the feature?  I've got an implementation that I'm using in my own personal composer role that I'd be happy to submit as a PR if you're open to the feature. That feature is just about the only thing keeping me from migrating to this role, so it'd be great to see support added.

**Comment by geerlingguy** [comment]
Yes, though one annoying nit I have here is that verifying the signature just means you're trusting `composer.github.io` a little more than just `getcomposer.org`. But it would add a slight bit more peace of mind to know that the download matches the expected signature, so I'd be willing to add support if it's something maintainable and idempotent.

Composer always does things a bit odd, though; it would be nice if there were just a SHA256, MD5, etc. that you could pick and choose, so that you can use prebuilt functionality to compare a hash (e.g. `get_url` with a `checksum`...).

**Comment by robinmalburn** [comment]
Doing things a bit odd is pretty much the mantra of PHP, I'm afraid.  Forcing the use of just SHA384 is a weird one (and also seems like something brittle if they change their mind about the algo in future).  I ended up using the `stat` module to handle the check_sum of the downloaded installer, since it supports SHA384 natively; I'm fairly new to Ansible and writing roles, though, so I appreciate that may not have been the most efficient way of doing things.  Having it just work via the `get_url` module would definitely feel cleaner if that were possible.
